### ISSUE TITLE
Make use of stderr?

### ISSUE THREAD

**Issue by ericsnowcurrently** [natefinch/plugin#1]
Looks like both Provide and Start drop stderr (os.Stderr and cmd.StderrPipe, respectively).  That's probably fine, since you can just say "stderr is ignored".  However, stderr could provide a channel to communicate error state instead of the complexity of requiring an error field on the "reply" struct (in Call).  Then again it would add complexity to ioPipe and rwcloser.  Using stderr for a second channel of communication also would make plugins less re-usable for HTTP RPC.

So, I'm not saying it is the right thing, but it is something to think about.

**Comment by natefinch** [comment]
You can't really use stderr for rpc from Go, unless you rewrite rpc... it currently just uses a reader and a writer.  The nice thing about that is that it leaves stderr for logging, which i think is pretty useful.
