### ISSUE TITLE
Support other codecs.

### ISSUE THREAD

**Issue by ericsnowcurrently** [natefinch/plugin#2]
The default codec (the gob wire format) is pretty Go-specific.  That means writing plugins in other programming languages isn't as easy.  If that matters then consider using something more universal, like XML-RPC or JSON-RPC.  This would require using NewClientWithCodec and Server.ServeCodec, as well as the correct ClientCodec implementation.  It might be a good idea to do this anyway (or in addition) so that the projects using this library can more easily choose their RPC format.

**Comment by natefinch** [comment]
using the JSON codec by default (and perhaps as the only codec) seems like a reasonable choice.  Definitely we want users to be able to write plugins in any language, and only Go really knows about gob, the default encoding.   I don't think the performance of gob is really critical in this application.  We could support arbitrary codecs, I guess, but I think the default should be json.

**Comment by natefinch** [comment]
Fixed.  Now we support gob by default and anything else with the various *WithCodec calls.  Gob has to be default, because there's no exposed way to create a Gob codec, for some reason.
